version: "3.5"

services:
  nginx:           
    container_name: vue-vite-template
    image: nginx:1.22.0
    restart: always
    ports:
      - 5858:8080
    volumes:
     -  ./dist:/nginxfile/dist
     -  ./conf.d:/etc/nginx/conf.d
     - ./log:/var/log/nginx
    environment:
    - TZ=Asia/Shanghai
